call plug#begin()
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

:filetype plugin on
let g:C_UseTool_cmake    = 'yes'
let g:C_UseTool_doxygen  = 'yes'
nnoremap <C-c> :!g++ -o  %:r.out % -std=c++2a -lpqxx -lpq<Enter>
nnoremap <C-x> :!./%:r.out

Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
Plug 'vim-scripts/taglist.vim'
Plug 'oblitum/rainbow'
Plug 'preservim/nerdcommenter'
Plug 'tpope/vim-surround'
Plug 'scrooloose/syntastic'
Plug 'octol/vim-cpp-enhanced-highlight'
call plug#end()
